### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by jrcacd** [kobeumut/UpdateChecker#6]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at com.grisoftware.updatechecker.GoogleChecker$1.run(GoogleChecker.java:126)

**Comment by kobeumut** [comment]
Hello @jrcacd , your app version is must be semantic like 1.0.4
If you think this is not the problem, can you also write the package name and the parameters you sent?

**Comment by jrcacd** [comment]
ok
